const config = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  safelist: [
    { pattern: /(bg|text|border|from|to)-(background|surface|surface-container-lowest|surface-container-low|surface-container-high|surface-container-highest|surface-variant|primary|primary-container|primary-fixed|primary-fixed-dim|on-primary|on-primary-container|on-primary-fixed|on-surface|on-surface-variant|on-background|secondary|secondary-container|secondary-fixed|secondary-fixed-dim|tertiary|tertiary-container|tertiary-fixed|tertiary-fixed-dim)(?:\/\d{1,3})?/ },
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#2d3449",
        "on-secondary-container": "#e6ecff",
        "inverse-on-surface": "#283044",
        secondary: "#adc6ff",
        error: "#ffb4ab",
        "on-background": "#dae2fd",
        "surface-bright": "#31394d",
        "on-primary-container": "#00422b",
        "outline-variant": "#3c4a42",
        surface: "#0b1326",
        "surface-variant": "#2d3449",
        outline: "#86948a",
        "on-primary": "#003824",
        "on-tertiary-fixed": "#410005",
        "inverse-surface": "#dae2fd",
        "on-surface": "#dae2fd",
        "primary-container": "#10b981",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#006c49",
        "on-error": "#690005",
        "on-surface-variant": "#bbcabf",
        "surface-container-high": "#222a3d",
        "secondary-container": "#0566d9",
        "surface-container-lowest": "#060e20",
        "on-tertiary": "#650911",
        "surface-container-low": "#131b2e",
        "tertiary-container": "#fc7c78",
        "error-container": "#93000a",
        background: "#0b1326",
        "primary-fixed": "#6ffbbe",
        "surface-tint": "#4edea3",
        tertiary: "#ffb3af",
        "on-primary-fixed": "#002113",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#711419",
        "surface-dim": "#0b1326",
        "surface-container": "#171f33",
        "on-secondary": "#002e6a",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d8e2ff",
        primary: "#4edea3",
        "on-secondary-fixed": "#001a42",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-fixed-variant": "#842225",
      },
      spacing: {
        sm: "16px",
        xs: "8px",
        "margin-desktop": "64px",
        base: "4px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
        lg: "48px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

module.exports = config;
